services:
  postgres:
    image: postgres:latest
    container_name: postgreSql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}

    volumes:
      - ./config/db_creation:/docker-entrypoint-initdb.d  
  blogging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microblogging
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres   
      POSTGRES_PORT: 5432       
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    volumes:
      - .:/app 