// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	model "microblogging/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BlogService is an autogenerated mock type for the BlogService type
type MockBlogService struct {
	mock.Mock
}

// CreatePost provides a mock function with given fields: userID, content
func (_m *MockBlogService) CreatePost(userID string, content string) (uuid.UUID, error) {
	ret := _m.Called(userID, content)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (uuid.UUID, error)); ok {
		return rf(userID, content)
	}
	if rf, ok := ret.Get(0).(func(string, string) uuid.UUID); ok {
		r0 = rf(userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: userData
func (_m *MockBlogService) CreateUser(userData model.CreateUserRequest) (uuid.UUID, error) {
	ret := _m.Called(userData)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(model.CreateUserRequest) (uuid.UUID, error)); ok {
		return rf(userData)
	}
	if rf, ok := ret.Get(0).(func(model.CreateUserRequest) uuid.UUID); ok {
		r0 = rf(userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(model.CreateUserRequest) error); ok {
		r1 = rf(userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: userID
func (_m *MockBlogService) DeleteUser(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowUser provides a mock function with given fields: followerID, followeeID
func (_m *MockBlogService) FollowUser(followerID string, followeeID string) error {
	ret := _m.Called(followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for FollowUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFollowees provides a mock function with given fields: userID, limit
func (_m *MockBlogService) GetFollowees(userID string, limit int) ([]string, error) {
	ret := _m.Called(userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowees")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]string, error)); ok {
		return rf(userID, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []string); ok {
		r0 = rf(userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimeline provides a mock function with given fields: timeLine
func (_m *MockBlogService) GetTimeline(timeLine model.TimelineRequest) (model.TimelineResponse, error) {
	ret := _m.Called(timeLine)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeline")
	}

	var r0 model.TimelineResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(model.TimelineRequest) (model.TimelineResponse, error)); ok {
		return rf(timeLine)
	}
	if rf, ok := ret.Get(0).(func(model.TimelineRequest) model.TimelineResponse); ok {
		r0 = rf(timeLine)
	} else {
		r0 = ret.Get(0).(model.TimelineResponse)
	}

	if rf, ok := ret.Get(1).(func(model.TimelineRequest) error); ok {
		r1 = rf(timeLine)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: userID
func (_m *MockBlogService) GetUser(userID string) (model.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnfollowUser provides a mock function with given fields: followerID, followeeID
func (_m *MockBlogService) UnfollowUser(followerID string, followeeID string) error {
	ret := _m.Called(followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for UnfollowUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePostPut provides a mock function with given fields: post
func (_m *MockBlogService) UpdatePostPut(post model.CreatePostRequest) error {
	ret := _m.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePostPut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.CreatePostRequest) error); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBlogService creates a new instance of MockBlogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlogService {
	mock := &MockBlogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
