name: Lint and Format Go Code

on:
  pull_request:
    paths:
      - '**.go'
  push:
    branches:
      - main

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Go and GolangCI-Lint
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.51.2/golangci-lint-1.51.2-linux-amd64.tar.gz | tar -xz -C /tmp
        sudo mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin/

    - name: Run GolangCI-Lint
      run: |
        golangci-lint run --fix

    - name: Run GoFmt
      run: |
        gofmt -s -w .

    - name: Check GoFmt
      run: |
        git diff --exit-code
